[package]
name = "keepEngine"
version = "0.1.0"
authors = ["Markus Ebner <hiwatari.seiji@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4"
regex = "1"
anyhow = "1"