[package]
name = "keepEngine"
version = "0.2.0"
authors = ["Markus Ebner <hiwatari.seiji@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["derive"] }
regex = "1"
anyhow = "1"
uuid = { version = "1", features = ["v4"] }

[profile.release]
opt-level = "s"
lto = "fat"
codegen-units = 1