#!/bin/bash

build() {
	add_checked_modules '/drivers/net/'

	add_binary "/usr/lib/initcpio/ipconfig" "/bin/ipconfig"
	add_binary "/usr/bin/mount.nfs4" "/bin/mount.nfs4"

	add_runscript
}

help() {
        cat <<HELPEOF
This installs our remountfs script.
HELPEOF
}
