#!/bin/bash

build() {
	add_checked_modules '/drivers/net/'
	add_module nfsv3?

	add_binary "/usr/lib/initcpio/ipconfig" "/bin/ipconfig"
	add_binary "/usr/lib/initcpio/nfsmount" "/bin/nfsmount"

	add_runscript
}

help() {
        cat <<HELPEOF
This installs our remountfs script.
HELPEOF
}