name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build Installer Script and Dependencies
        run: |
          pushd bin/keepEngine
          cargo build --release
          popd
          cp bin/keepEngine/target/release/keepEngine res/lapas/guest/lapas/
          chmod +x res/lapas/guest/lapas/keepEngine
          python3 ./make.py > ./lapas_installer.sh
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ github.token }}"
          prerelease: false
          title: "LAPAS Installer [${{ github.ref_name }}]"
          automatic_release_tag: "${{ github.ref_name }}"
          files: |
            lapas_installer.sh
