name: Release Nightly
on:
  push:
    branches:
      - "master"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
      - name: Build Installer Script and Dependencies
        run: |
          pushd bin/keepEngine
          cargo build --target x86_64-unknown-linux-musl --release
          popd
          cp bin/keepEngine/target/release/keepEngine res/lapas/guest/lapas/
          chmod +x res/lapas/guest/lapas/keepEngine
          python3 ./make.py > ./lapas_installer.sh
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ github.token }}"
          automatic_release_tag: "nightly"
          prerelease: true
          title: "LAPAS Installer [nightly]"
          files: |
            lapas_installer.sh
